from framework.training.batch_generator.homogenous_cluster_training import homogenous_cluster_training 
from framework.training.batch_generator.inhomogenous_cluster_training import inhomogenous_cluster_training 
