from framework.data_manager import enzyme_data_manager
from framework.data_manager import enzyme_protein_data_manager
from framework.data_manager import undeleted_enzyme_data_manager
from framework.data_manager import new_enzyme_data_manager
from framework.data_manager import get_pairs_manager 
